### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by Ay-Cho-Cho** [Ritwik-Gupta/Sensor-Fault-Detection-#1]
Hi Gupta, I just wanted to know more about your project and if it is complete. I'll be working on something similar i just need to understand better

**Comment by Ay-Cho-Cho** [comment]
> Hi Gupta, I just wanted to know more about your project and if it is complete. I'll be working on something similar i just need to understand better

@Ritwik-Gupta

**Comment by rgupta07** [comment]
Hi , yes I had completed it , but it has been quite a while.
Let me know what if you need help

**Comment by Ay-Cho-Cho** [comment]
> Hi , yes I had completed it , but it has been quite a while. Let me know what if you need help

I downloaded your code and tried to run it but it has been bringing an error that has to do with MongoDB 
You can share your email so I can just text you directly
@Ritwik-Gupta

**Comment by Ay-Cho-Cho** [comment]
@Ritwik-Gupta 

> > Hi , yes I had completed it , but it has been quite a while. Let me know what if you need help
> 
> I downloaded your code and tried to run it but it has been bringing an error that has to do with MongoDB You can share your email so I can just text you directly @Ritwik-Gupta

**Comment by rgupta07** [comment]
Hi, mail me here ritwik94348gupta@gmail.com

**Comment by Ay-Cho-Cho** [comment]
I already texted you through your mail @Ritwik-Gupta

**Comment by Ay-Cho-Cho** [comment]
This is the new error i got after fixing the MongoDB issue:

PS C:\Users\850 elite\Pictures\Illustrator\Sensor-main> python main.py
Loading environment variable from .env file
Traceback (most recent call last):
  File "C:\Users\850 elite\Pictures\Illustrator\Sensor-main\sensor\components\data_ingestion.py", line 42, in initiate_data_ingestion
    train_data, test_data = train_test_split(df, test_size=self.data_ingestion_config.test_size, random_state=42)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\850 elite\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\_param_validation.py", line 214, in wrapper       
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\850 elite\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_split.py", line 2649, in train_test_split
    n_train, n_test = _validate_shuffle_split(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\850 elite\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_split.py", line 2305, in _validate_shuffle_split
    raise ValueError(
ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\850 elite\Pictures\Illustrator\Sensor-main\main.py", line 22, in <module>
    data_ingestion_artifact = data_ingestion.initiate_data_ingestion()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\850 elite\Pictures\Illustrator\Sensor-main\sensor\components\data_ingestion.py", line 56, in initiate_data_ingestion
    raise SensorException(ex, sys)
sensor.exception.SensorException: Error occurred python script name [C:\Users\850 elite\Pictures\Illustrator\Sensor-main\sensor\components\data_ingestion.py] line number [42] error message [With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\850 elite\Pictures\Illustrator\Sensor-main\main.py", line 53, in <module>
    raise SensorException(ex, sys)
sensor.exception.SensorException: Error occurred python script name [C:\Users\850 elite\Pictures\Illustrator\Sensor-main\main.py] line number [22] error message [Error occurred python script name [C:\Users\850 elite\Pictures\Illustrator\Sensor-main\sensor\components\data_ingestion.py] line number 
[42] error message [With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.]]

**Comment by Ay-Cho-Cho** [comment]
> Hi, mail me here [ritwik94348gupta@gmail.com](mailto:ritwik94348gupta@gmail.com)

I've mailed you but no response, maybe you just share where you are always active so i can connect with you.
The issue I'm having is concerning the data retrieval 
I do not know much about MongoDB but it seems the data in the database is not included in your repository

@Ritwik-Gupta Please respond.
